### Aufgaben

In [10]:
import numpy as np
from sympy import Matrix,eye,linsolve
from scipy import linalg
np.set_printoptions(precision=2, suppress= True)

### A1

Löse Ax = b mit einer einfachen Linearkombination

In [3]:
A = np.array([1,1,-2,1,-1,2,3,1,0]).reshape(3,3)

In [4]:
# a
x = np.array([1,-1,0]).reshape(3,1)
b = A.dot(x)
A, b

(array([[ 1,  1, -2],
        [ 1, -1,  2],
        [ 3,  1,  0]]),
 array([[0],
        [2],
        [2]]))

In [6]:
# b
x = np.array([0,1,1]).reshape(3,1)
b = A.dot(x)
A, b

(array([[ 1,  1, -2],
        [ 1, -1,  2],
        [ 3,  1,  0]]),
 array([[-1],
        [ 1],
        [ 1]]))

In [7]:
# c
x = np.array([-1,1,1]).reshape(3,1)
b = A.dot(x)
A, b

(array([[ 1,  1, -2],
        [ 1, -1,  2],
        [ 3,  1,  0]]),
 array([[-2],
        [ 0],
        [-2]]))

In [111]:
def ele(k,i,l,j,n=3):
    # ändert nur zeile i: vom k fachen der zeile i wird das l-fache der zeile j abgezogen
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = -l
    return tmp

def permut(i,j,n): 
    tmp = np.identity(n)
    tmp[i-1],tmp[j-1] = tmp[j-1].copy(),tmp[i-1].copy()
    return tmp.astype(int)
    

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 1.],
       [0., 0., 1., 7.]])

### A2 
Löse mit Elimination und Rücksubstitution

In [40]:
A = np.array([2,1,-2,-1,-2,2,3,0,-1]).reshape(3,3)
x = np.array([3,-4,2]).reshape(3,1)
b = A @ x
A, b


(array([[ 2,  1, -2],
        [-1, -2,  2],
        [ 3,  0, -1]]),
 array([[-2],
        [ 9],
        [ 7]]))

In [43]:
t = np.append(A,b,axis=1)
t = ele(-2,2,1,1) @ t
t = ele(2,3,3,1) @ t
t = ele(1,3,-1,2) @ t
t

array([[  2.,   1.,  -2.,  -2.],
       [  0.,   3.,  -2., -16.],
       [  0.,   0.,   2.,   4.]])

In [49]:
# b
A = np.array([2,-4,5,3,3,7,4,-2,-3]).reshape(3,3)
x = np.array([1,2,1]).reshape(3,1)
b = A @ x
A, b

(array([[ 2, -4,  5],
        [ 3,  3,  7],
        [ 4, -2, -3]]),
 array([[-1],
        [16],
        [-3]]))

In [51]:
t = np.append(A,b,axis=1)
t = ele(2,2,3,1) @ t
t = ele(1,3,2,1) @ t
t = ele(3,3,1,2) @ t
t

array([[  2.,  -4.,   5.,  -1.],
       [  0.,  18.,  -1.,  35.],
       [  0.,   0., -38., -38.]])

### A3 Matrixmultiplikation

In [113]:
a = np.array([1,2,3,4,3,2,1,4,2]).reshape(3,3)
b = np.array([3,1,2,1,2,0,1,0,1,1,3,0]).reshape(3,4)
A = Matrix(a)
B = Matrix(b)
C = A * B

In [114]:
A

Matrix([
[1, 2, 3],
[4, 3, 2],
[1, 4, 2]])

In [115]:
B

Matrix([
[3, 1, 2, 1],
[2, 0, 1, 0],
[1, 1, 3, 0]])

In [116]:
C

Matrix([
[10, 4, 13, 1],
[20, 6, 17, 4],
[13, 3, 12, 1]])

In [9]:
a = np.array([1,2,3,4,3,2,1,4]).reshape(4,2)
b = np.array([3,1,2,1,2,0]).reshape(2,3)
A = Matrix(a)
B = Matrix(b)
C = A * B

In [10]:
A

Matrix([
[1, 2],
[3, 4],
[3, 2],
[1, 4]])

In [11]:
B

Matrix([
[3, 1, 2],
[1, 2, 0]])

In [12]:
C

Matrix([
[ 5,  5, 2],
[13, 11, 6],
[11,  7, 6],
[ 7,  9, 2]])

### A4

In [133]:
# Vertausche Zeile 1 und 2
# Ziehe von Zeile 2 das 3-fache von Zeile 1 ab
# Ziehe von Zeile 3 das -2-fache von Zeile 1 ab
# Ziehe von Zeile 3 das -1-fache von Zeile 2 ab


u = np.array([1,2,3,0,-1,0,0,0,-1]).reshape(3,3)
e21 = ele(1,2,3,1)
e31 = ele(1,3,-2,1)
e32 = ele(1,3,-1,2) 
p =  permut(1,2,3)
a = p @ np.linalg.inv(e32) @ np.linalg.inv(e31) @ np.linalg.inv(e21) @ u
u, a, e21, e31, e32, p

(array([[ 1,  2,  3],
        [ 0, -1,  0],
        [ 0,  0, -1]]),
 array([[  3.,   5.,   9.],
        [  1.,   2.,   3.],
        [ -5.,  -9., -16.]]),
 array([[ 1.,  0.,  0.],
        [-3.,  1.,  0.],
        [ 0.,  0.,  1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [2., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 1.]]),
 array([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]]))

In [134]:
# Vertausche Zeile 1 und 2
# Ziehe von Zeile 2 das 3-fache von Zeile 1 ab
# Ziehe von Zeile 3 das -2-fache von Zeile 1 ab
# Ziehe von Zeile 3 das -1-fache von Zeile 2 ab

u = np.array([2,1,5,0,4,3,0,0,6]).reshape(3,3)
p = permut(2,3,3)
e21 = ele(2,2,5,1)
e31 = ele(1,3,-1,1)
e32 = ele(2,3,7,2) 
a = p @ np.linalg.inv(e32) @ np.linalg.inv(e31) @ np.linalg.inv(e21) @ u
u, a, e21, e31, e32, p

(array([[2, 1, 5],
        [0, 4, 3],
        [0, 0, 6]]),
 array([[ 2.  ,  1.  ,  5.  ],
        [16.5 , 15.25, 49.5 ],
        [ 5.  ,  4.5 , 14.  ]]),
 array([[ 1.,  0.,  0.],
        [-5.,  2.,  0.],
        [ 0.,  0.,  1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 1.]]),
 array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0., -7.,  2.]]),
 array([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]]))

### A5   
LU - Faktorisierung an einfachen Beispielen



In [58]:
# a.
u = np.array([1,3,2,0,3,-1,0,0,4]).reshape(3,3)
l = np.array([1,0,0,-2,1,0,0,3,1]).reshape(3,3)
a = l@u.astype(int)
a, l, u

(array([[ 1,  3,  2],
        [-2, -3, -5],
        [ 0,  9,  1]]),
 array([[ 1,  0,  0],
        [-2,  1,  0],
        [ 0,  3,  1]]),
 array([[ 1,  3,  2],
        [ 0,  3, -1],
        [ 0,  0,  4]]))

In [59]:
Matrix(a)

Matrix([
[ 1,  3,  2],
[-2, -3, -5],
[ 0,  9,  1]])

Die Berechnung

In [39]:
t = el(2,-2,1).dot(a)                    # von der 2.zeile ziehe ich das -2-fache der 1.zeile ab
Matrix(t.astype(int))

Matrix([
[1, 3,  2],
[0, 3, -1],
[0, 9,  1]])

In [40]:
Matrix(el(2,-2,1))

Matrix([
[1, 0, 0],
[2, 1, 0],
[0, 0, 1]])

In [41]:
t = el(3,3,2).dot(el(2,-2,1).dot(A))     # von der 3.zeile ziehe ich das 3-fache der 2.zeile ab
Matrix(t.astype(int))

Matrix([
[1, 3,  2],
[0, 3, -1],
[0, 0,  4]])

In [42]:
Matrix(el(3,3,2))

Matrix([
[1,  0, 0],
[0,  1, 0],
[0, -3, 1]])

In [43]:
L = np.linalg.inv((el(3,3,2).dot(el(2,-2,1))))
Matrix(L.astype(int))

Matrix([
[ 1, 0, 0],
[-2, 1, 0],
[ 0, 3, 1]])

Noch eine Kontrolle

In [44]:
Matrix(A).LUdecomposition()


(Matrix([
 [ 1, 0, 0],
 [-2, 1, 0],
 [ 0, 3, 1]]),
 Matrix([
 [1, 3,  2],
 [0, 3, -1],
 [0, 0,  4]]),
 [])

In [60]:
# b.
 
u = np.array([1,-1,1,0,-1,1,0,0,2]).reshape(3,3)
l = np.array([1,0,0,-1,1,0,1,2,1]).reshape(3,3)
a = l@u.astype(int)
a, l, u

(array([[ 1, -1,  1],
        [-1,  0,  0],
        [ 1, -3,  5]]),
 array([[ 1,  0,  0],
        [-1,  1,  0],
        [ 1,  2,  1]]),
 array([[ 1, -1,  1],
        [ 0, -1,  1],
        [ 0,  0,  2]]))

In [61]:
Matrix(a)

Matrix([
[ 1, -1, 1],
[-1,  0, 0],
[ 1, -3, 5]])

In [62]:
t = el(2,-1,1)@ a
Matrix(t.astype(int))

Matrix([
[1, -1, 1],
[0, -1, 1],
[1, -3, 5]])

In [63]:
t = el(3,1,1) @ t
Matrix(t.astype(int))

Matrix([
[1, -1, 1],
[0, -1, 1],
[0, -2, 4]])

In [64]:
t = el(3,2,2) @ t
Matrix(t.astype(int))

Matrix([
[1, -1, 1],
[0, -1, 1],
[0,  0, 2]])

In [67]:
Matrix(a).LUdecomposition()[0]

Matrix([
[ 1, 0, 0],
[-1, 1, 0],
[ 1, 2, 1]])

### A6

In [2]:
def intMatrix(A):
    # true wenn alles ganzzahlig
    return np.all(A - A.astype(int) == 0)

def augment(a):
    n = a.shape[0]
    return np.append(a, np.eye(n), axis=1)

def el(i,k,j,n=3):    # 3x3 Eliminations-Matrix 
    # von der i-ten Zeile, das k-fache der j-ten Zeile abziehen
    tmp = np.eye(n)
    tmp[i-1,j-1] = -k
    return tmp.astype(int)

def ele(k,i,l,j,n=3):
    # ändert nur zeile i: vom k fachen der zeile i wird das l-fache der zeile j abgezogen
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = -l
    return tmp

def rm(r,k,n=3):
    # returns Matrix which multiplies row r of a nxn Matrix with scalar k 
    tmp = np.eye(n)
    tmp[r-1,r-1]= k
    return tmp

def permut(i,j,n): 
    tmp = np.identity(n)
    tmp[i-1],tmp[j-1] = tmp[j-1].copy(),tmp[i-1].copy()
    return tmp.astype(int)

In [23]:
for i in range(10000):
    # ganzzahlige invertierbare 3x3 Matrizen
    x = np.random.randint(-4,4,9) 
    x = x.reshape(3,3)
    if abs(linalg.det(x)) > 1 and intMatrix(linalg.inv(x)):
        print(list(x.flatten()))
        


[1, -3, 1, 2, 0, 1, -1, -4, 0]
[-4, -2, 3, 1, 1, 1, 0, 1, 3]
[-1, 2, -3, 1, -3, -4, 1, -2, 2]
[-4, -3, 1, -1, 3, 3, -3, -2, 1]
[-1, 0, 3, 1, -1, -3, -1, -4, 2]
[-3, -2, 2, 1, -2, -1, 0, 1, 0]
[3, 1, -1, -4, 0, 3, 0, 1, 1]
[-1, 3, 3, 1, -2, 1, -1, 2, 0]
[2, -2, 3, 0, 1, 1, 1, -2, 1]
[-1, -2, 3, 0, 1, -1, 3, -2, 0]
[1, 3, 1, -1, 3, -2, 1, 2, 1]
[0, 1, -2, 1, -1, -1, -2, 3, -1]
[3, 0, -2, -4, 0, 3, -2, 1, -3]
[0, -1, -3, -1, 2, 1, -1, 1, -1]


In [40]:
# a
a = np.array([1, 3, 1, 0, 1, 2, 1, 3, 2]).reshape(3,3)
Matrix(a)

Matrix([
[1, 3, 1],
[0, 1, 2],
[1, 3, 2]])

In [24]:
Matrix(linalg.inv(a).astype(int))

Matrix([
[-4, -3,  5],
[ 2,  1, -2],
[-1,  0,  1]])

In [29]:
t = augment(a)
Matrix(t.astype(int))

Matrix([
[1, 3, 1, 1, 0, 0],
[0, 1, 2, 0, 1, 0],
[1, 3, 2, 0, 0, 1]])

In [30]:
t = el(3,1,1) @ t
Matrix(t.astype(int))

Matrix([
[1, 3, 1,  1, 0, 0],
[0, 1, 2,  0, 1, 0],
[0, 0, 1, -1, 0, 1]])

In [31]:
t = el(2,2,3) @ t
Matrix(t.astype(int))

Matrix([
[1, 3, 1,  1, 0,  0],
[0, 1, 0,  2, 1, -2],
[0, 0, 1, -1, 0,  1]])

In [32]:
t = el(1,1,3) @ t
Matrix(t.astype(int))

Matrix([
[1, 3, 0,  2, 0, -1],
[0, 1, 0,  2, 1, -2],
[0, 0, 1, -1, 0,  1]])

In [33]:
t = el(1,3,2) @ t
Matrix(t.astype(int))

Matrix([
[1, 0, 0, -4, -3,  5],
[0, 1, 0,  2,  1, -2],
[0, 0, 1, -1,  0,  1]])

In [51]:
# b

a = np.array([3, 2, 2, -3, -4, -3, -4, -3, -3]).reshape(3,3)
Matrix(a)

Matrix([
[ 3,  2,  2],
[-3, -4, -3],
[-4, -3, -3]])

In [52]:
Matrix(linalg.inv(a).astype(int))

Matrix([
[ 3,  0,  2],
[ 3, -1,  3],
[-7,  1, -6]])

In [53]:
t = augment(a)
Matrix(t.astype(int))

Matrix([
[ 3,  2,  2, 1, 0, 0],
[-3, -4, -3, 0, 1, 0],
[-4, -3, -3, 0, 0, 1]])

In [54]:
t = el(2,-1,1) @ t
Matrix(t.astype(int))

Matrix([
[ 3,  2,  2, 1, 0, 0],
[ 0, -2, -1, 1, 1, 0],
[-4, -3, -3, 0, 0, 1]])

In [55]:
t = ele(3,3,-4,1) @ t
Matrix(t.astype(int))

Matrix([
[3,  2,  2, 1, 0, 0],
[0, -2, -1, 1, 1, 0],
[0, -1, -1, 4, 0, 3]])

In [56]:
t = ele(2,3,1,2) @ t
Matrix(t.astype(int))

Matrix([
[3,  2,  2, 1,  0, 0],
[0, -2, -1, 1,  1, 0],
[0,  0, -1, 7, -1, 6]])

In [57]:
t = el(2,1,3) @ t
Matrix(t.astype(int))

Matrix([
[3,  2,  2,  1,  0,  0],
[0, -2,  0, -6,  2, -6],
[0,  0, -1,  7, -1,  6]])

In [58]:
t = el(1,-2,3) @ t
Matrix(t.astype(int))

Matrix([
[3,  2,  0, 15, -2, 12],
[0, -2,  0, -6,  2, -6],
[0,  0, -1,  7, -1,  6]])

In [59]:
t = el(1,-1,2) @ t
Matrix(t.astype(int))

Matrix([
[3,  0,  0,  9,  0,  6],
[0, -2,  0, -6,  2, -6],
[0,  0, -1,  7, -1,  6]])

In [60]:
t = rm(1,1/3) @ t
t = rm(2,-1/2) @ t 
t = rm(3,-1) @ t 
Matrix(t.astype(int))

Matrix([
[1, 0, 0,  3,  0,  2],
[0, 1, 0,  3, -1,  3],
[0, 0, 1, -7,  1, -6]])

### A7
Permutationen

In [73]:
a = np.identity(5).astype(int)
Matrix(a)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [76]:
# a.
Matrix(permut(2,3,5) @ permut(5,2,5) @ permut(1,4,5))

Matrix([
[0, 0, 0, 1, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 0, 1],
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0]])

In [78]:
# b.
Matrix(permut(4,5,5) @ permut(1,3,5)) 

Matrix([
[0, 0, 1, 0, 0],
[0, 1, 0, 0, 0],
[1, 0, 0, 0, 0],
[0, 0, 0, 0, 1],
[0, 0, 0, 1, 0]])

### A8

Alle Lösungen von Ax = b

In [48]:
# a.
a = np.array([1,3,0,2,0,0,1,4,1,3,1,6]).reshape(3,4)
Matrix(a)
b = np.array([1,6,7]).reshape(3,1)
a, b

(array([[1, 3, 0, 2],
        [0, 0, 1, 4],
        [1, 3, 1, 6]]),
 array([[1],
        [6],
        [7]]))

In [49]:
Matrix(a).nullspace()

[Matrix([
 [-3],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [-2],
 [ 0],
 [-4],
 [ 1]])]

In [34]:
linsolve((Matrix(a),Matrix(b)))

FiniteSet((-3*tau0 - 2*tau1 + 1, tau0, 6 - 4*tau1, tau1))

In [51]:
t = np.append(a,b,axis=1)
Matrix(t)

Matrix([
[1, 3, 0, 2, 1],
[0, 0, 1, 4, 6],
[1, 3, 1, 6, 7]])

In [52]:
t = el(3,1,1) @ t
Matrix(t)

Matrix([
[1, 3, 0, 2, 1],
[0, 0, 1, 4, 6],
[0, 0, 1, 4, 6]])

In [53]:
t = el(3,1,2) @ t
Matrix(t)

Matrix([
[1, 3, 0, 2, 1],
[0, 0, 1, 4, 6],
[0, 0, 0, 0, 0]])

In [39]:
# b. 
a = np.array([1,2,3,5,2,4,8,12,3,6,7,13]).reshape(3,4)
b = np.array([0,6,-6]).reshape(3,1)

Matrix(a).nullspace()

[Matrix([
 [-2],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [-2],
 [ 0],
 [-1],
 [ 1]])]

In [44]:
t = np.append(a,b,axis=1)
Matrix(t)

Matrix([
[1, 2, 3,  5,  0],
[2, 4, 8, 12,  6],
[3, 6, 7, 13, -6]])

In [45]:
t = el(2,2,1) @ t
Matrix(t)

Matrix([
[1, 2, 3,  5,  0],
[0, 0, 2,  2,  6],
[3, 6, 7, 13, -6]])

In [46]:
t = el(3,3,1) @ t
Matrix(t)

Matrix([
[1, 2,  3,  5,  0],
[0, 0,  2,  2,  6],
[0, 0, -2, -2, -6]])

In [47]:
t = el(3,-1,2) @ t
Matrix(t)

Matrix([
[1, 2, 3, 5, 0],
[0, 0, 2, 2, 6],
[0, 0, 0, 0, 0]])

In [15]:
linsolve((Matrix(a),Matrix(b)))

FiniteSet((-2*tau0 - 2*tau1 - 9, tau0, 3 - tau1, tau1))

### A9

Dimension von Kern und Bild bestimmen

In [63]:
#a.

v1 = np.array([3,1,2,-1])
v2 = np.array([1,1,-1,2])
v3 = 2*v1-2*v2
v4 = 2*v3+v2-2*v1
v5 = 2*v2-v4-v1
a = np.array([v1,v2,v3,v4,v5])
a = a.T
Matrix(a)

Matrix([
[ 3,  1,  4,  3,  -4],
[ 1,  1,  0, -1,   2],
[ 2, -1,  6,  7, -11],
[-1,  2, -6, -8,  13]])

In [64]:
Matrix(a).rref()[0]

Matrix([
[1, 0,  2,  2, -3],
[0, 1, -2, -3,  5],
[0, 0,  0,  0,  0],
[0, 0,  0,  0,  0]])

In [65]:
Matrix(a).nullspace()

[Matrix([
 [-2],
 [ 2],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [-2],
 [ 3],
 [ 0],
 [ 1],
 [ 0]]),
 Matrix([
 [ 3],
 [-5],
 [ 0],
 [ 0],
 [ 1]])]

In [76]:
# b

v1 = np.array([2,1,2,-1])
v2 = np.array([3,0,-1,-2])
v3 = v1 -2*v2
v4 = np.array([2,1,-1,2])
 
a = np.array([v1,v2,v3,v4])
a = a.T
Matrix(a)

Matrix([
[ 2,  3, -4,  2],
[ 1,  0,  1,  1],
[ 2, -1,  4, -1],
[-1, -2,  3,  2]])

In [77]:
Matrix(a).rref()[0]

Matrix([
[1, 0,  1, 0],
[0, 1, -2, 0],
[0, 0,  0, 1],
[0, 0,  0, 0]])

In [78]:
Matrix(a).nullspace()

[Matrix([
 [-1],
 [ 2],
 [ 1],
 [ 0]])]

### Elimination als Matrixoperationen

In [112]:
t = Matrix(permut(2,3,3))
t

Matrix([
[1, 0, 0],
[0, 0, 1],
[0, 1, 0]])

In [ ]:
t = per

In [27]:
l = np.array([1,2,1,3,0,3,2,1,0,0,1,2,0,0,0,3]).reshape(4,4)
L = Matrix(l)
L

Matrix([
[1, 2, 1, 3],
[0, 3, 2, 1],
[0, 0, 1, 2],
[0, 0, 0, 3]])

In [28]:
e21 = np.identity(4)
e21[1,0]=-2
e21 = e21.astype(int)
E21 = Matrix(e21)
E21

Matrix([
[ 1, 0, 0, 0],
[-2, 1, 0, 0],
[ 0, 0, 1, 0],
[ 0, 0, 0, 1]])

In [29]:
p34 = np.array([1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0]).reshape(4,4)
P34 = Matrix(p34)
P34

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 1],
[0, 0, 1, 0]])

In [30]:
e32 = np.identity(4)
e32[2,1]= 3
e32 = e32.astype(int)
E32 = Matrix(e32)
E32

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 3, 1, 0],
[0, 0, 0, 1]])

In [75]:
A = E21.inv() * E32.inv() * P34.inv() * L
A

Matrix([
[1,  2,  1, 3],
[2,  7,  4, 7],
[0, -9, -6, 0],
[0,  0,  1, 2]])

In [91]:
t = np.array(A).astype(int)
t

array([[ 1,  2,  1,  3],
       [ 2,  7,  4,  7],
       [ 0, -9, -6,  0],
       [ 0,  0,  1,  2]])

In [92]:
t = ele(1,2,2,1,n=4) @ t
t

array([[ 1.,  2.,  1.,  3.],
       [ 0.,  3.,  2.,  1.],
       [ 0., -9., -6.,  0.],
       [ 0.,  0.,  1.,  2.]])

In [93]:
t = ele(1,3,-3,2,n=4) @ t
t

array([[1., 2., 1., 3.],
       [0., 3., 2., 1.],
       [0., 0., 0., 3.],
       [0., 0., 1., 2.]])

In [95]:
t = permut(3,4,4) @ t
t

array([[1., 2., 1., 3.],
       [0., 3., 2., 1.],
       [0., 0., 1., 2.],
       [0., 0., 0., 3.]])

In [100]:
t = np.array(A).astype(int)
t

array([[ 1,  2,  1,  3],
       [ 2,  7,  4,  7],
       [ 0, -9, -6,  0],
       [ 0,  0,  1,  2]])

In [101]:
t = ele(1,2,2,1,n=4) @ t
t

array([[ 1.,  2.,  1.,  3.],
       [ 0.,  3.,  2.,  1.],
       [ 0., -9., -6.,  0.],
       [ 0.,  0.,  1.,  2.]])

In [99]:
t = ele(1,3,-3,2,n=4) @ t
t

array([[ 1.,  2.,  1.,  3.],
       [ 0.,  3.,  2.,  1.],
       [ 0.,  9.,  7.,  5.],
       [ 0., -9., -6.,  0.]])

### A?

LU - Faktorisierung an einfachen Beispielen

In [66]:
A, L, U

(array([[ 1,  3,  2],
        [-2, -3, -5],
        [ 0,  9,  1]]),
 array([[ 1,  0,  0],
        [-2,  1,  0],
        [ 0,  3,  1]]),
 array([[ 1,  3,  2],
        [ 0,  3, -1],
        [ 0,  0,  4]]))

In [71]:
# b
U = np.array([1,4,-1,0,2,-2,0,0,3]).reshape(3,3)
L = np.array([1,0,0,-3,1,0,2,-1,1]).reshape(3,3)
A = L.dot(U)
A, L, U

(array([[  1,   4,  -1],
        [ -3, -10,   1],
        [  2,   6,   3]]),
 array([[ 1,  0,  0],
        [-3,  1,  0],
        [ 2, -1,  1]]),
 array([[ 1,  4, -1],
        [ 0,  2, -2],
        [ 0,  0,  3]]))

In [72]:
Matrix(A).LUdecomposition()

(Matrix([
 [ 1,  0, 0],
 [-3,  1, 0],
 [ 2, -1, 1]]),
 Matrix([
 [1, 4, -1],
 [0, 2, -2],
 [0, 0,  3]]),
 [])

### A4

Gegeben die Matrix A und die Matrix U und eine Beschreibung der Operationen. Bestimme Matrix L

Eine 4x4 Matrix

In [86]:
A = np.array([1,2,-1,1,2,1,1,2,-1,4,-1,-1,2,1,5,0]).reshape(4,4)
A

array([[ 1,  2, -1,  1],
       [ 2,  1,  1,  2],
       [-1,  4, -1, -1],
       [ 2,  1,  5,  0]])

In [87]:
L, U, _ = Matrix(A).LUdecomposition()
L

Matrix([
[ 1,  0, 0, 0],
[ 2,  1, 0, 0],
[-1, -2, 1, 0],
[ 2,  1, 1, 1]])

In [88]:
A

array([[ 1,  2, -1,  1],
       [ 2,  1,  1,  2],
       [-1,  4, -1, -1],
       [ 2,  1,  5,  0]])

In [97]:
t = el(2,2,1,4).dot(A)
t = el(3,-1,1,4).dot(t)
t = el(4,2,1,4).dot(t)
t = el(3,-2,2,4).dot(t)
t = el(4,1,2,4).dot(t)
t = el(4,1,3,4).dot(t)
t

array([[ 1.,  2., -1.,  1.],
       [ 0., -3.,  3.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0., -2.]])

In [98]:
Matrix(A).LUdecomposition()

(Matrix([
 [ 1,  0, 0, 0],
 [ 2,  1, 0, 0],
 [-1, -2, 1, 0],
 [ 2,  1, 1, 1]]),
 Matrix([
 [1,  2, -1,  1],
 [0, -3,  3,  0],
 [0,  0,  4,  0],
 [0,  0,  0, -2]]),
 [])

### Die Inverse einer quadratischen Matrix

Gauss-Jordan Algorithmus

### Lösungen für Ax = b