In [1]:
from sympy import Matrix 
import numpy as np
from scipy import linalg
np.set_printoptions(precision=2, suppress= True)

In [2]:
def ele2(k,i,l,j,n=3):
    # ändert nur zeile i: vom k fachen der zeile i wird das l-fache der zeile j abgezogen
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = -l
    return tmp

def ele(i,l,j,n=3):
    # ziehe von zeile i das l-fache von zeile j ab.
    tmp = np.eye(n)
    tmp[i-1,j-1] = -l
    return tmp

def permut(i,j,n): 
    tmp = np.identity(n)
    tmp[i-1],tmp[j-1] = tmp[j-1].copy(),tmp[i-1].copy()
    return tmp.astype(int)

In [3]:
def gadd(k,i,l,j,n=3):
    # addiere zum k-fachen der zeile i das l-fache der zeile j
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = l
    return tmp

def gsub(k,i,l,j,n=3):
    # subtrahiere vom k-fachen der zeile i das l-fache der zeile j
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = -l
    return tmp

### Zeilen und Spaltensicht

In [4]:
a = np.array([1,2,1,2,3,8,1,12,0,4,1,2]).reshape(3,4)
a

array([[ 1,  2,  1,  2],
       [ 3,  8,  1, 12],
       [ 0,  4,  1,  2]])

In [5]:
t = ele(2,3,1) @ a
t

array([[ 1.,  2.,  1.,  2.],
       [ 0.,  2., -2.,  6.],
       [ 0.,  4.,  1.,  2.]])

In [6]:
t = ele(3,2,2) @ t
t

array([[  1.,   2.,   1.,   2.],
       [  0.,   2.,  -2.,   6.],
       [  0.,   0.,   5., -10.]])

### Die Schritte des Gauss-Verfahrens als Matrizenoperationen

In [7]:
u = np.array([2,1,2,0,1,-1,0,0,3]).reshape(3,3)
l = np.array([1,0,0,-1,1,0,2,2,1]).reshape(3,3)
a = l @ u
Matrix(a)

Matrix([
[ 2, 1,  2],
[-2, 0, -3],
[ 4, 4,  5]])

In [8]:
Matrix(u)

Matrix([
[2, 1,  2],
[0, 1, -1],
[0, 0,  3]])

In [9]:
Matrix(l)

Matrix([
[ 1, 0, 0],
[-1, 1, 0],
[ 2, 2, 1]])

In [10]:
t = ele(2,-1,1) @ a
t = ele(3,2,1) @ t
t = ele(3,2,2) @ t
t

array([[ 2.,  1.,  2.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  3.]])

Beispiel im Script

In [11]:
a = np.array([1,2,3,2,4,7,1,1,3]).reshape(3,3)
a

array([[1, 2, 3],
       [2, 4, 7],
       [1, 1, 3]])

In [12]:
t = ele(2,2,1) @ a
t = ele(3,1,1) @ t 
t


array([[ 1.,  2.,  3.],
       [ 0.,  0.,  1.],
       [ 0., -1.,  0.]])

In [13]:
t = permut(2,3,3) @ t
t

array([[ 1.,  2.,  3.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
Matrix(a)

Matrix([
[1, 2, 3],
[2, 4, 7],
[1, 1, 3]])

In [15]:
Matrix(t.astype(int))

Matrix([
[1,  2, 3],
[0, -1, 0],
[0,  0, 1]])

In [16]:
Matrix((ele(3,1,1) @ ele(2,2,1)).astype(int))

Matrix([
[ 1, 0, 0],
[-2, 1, 0],
[-1, 0, 1]])

### Matrix-Multiplikation

In [17]:
a = np.array([1,2,3,4,3,2,1,4,2]).reshape(3,3)
b = np.array([3,1,2,1,2,0,1,0,1,1,3,0]).reshape(3,4)
A = Matrix(a)
B = Matrix(b)
C = A * B

In [18]:
A

Matrix([
[1, 2, 3],
[4, 3, 2],
[1, 4, 2]])

In [19]:
B

Matrix([
[3, 1, 2, 1],
[2, 0, 1, 0],
[1, 1, 3, 0]])

In [20]:
C

Matrix([
[10, 4, 13, 1],
[20, 6, 17, 4],
[13, 3, 12, 1]])

#### Matrix-Multiplikation ist nicht kommutativ




In [28]:
a = np.array([1,0,0,1,0,0,1,0,0]).reshape(3,3)
b = np.array([2,0,0,0,0,0,0,0,0]).reshape(3,3)

Matrix(a)

Matrix([
[1, 0, 0],
[1, 0, 0],
[1, 0, 0]])

In [30]:
Matrix(b)

Matrix([
[2, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [31]:
Matrix(a@b)

Matrix([
[2, 0, 0],
[2, 0, 0],
[2, 0, 0]])

In [32]:
Matrix(b@a)

Matrix([
[2, 0, 0],
[0, 0, 0],
[0, 0, 0]])

### Vertauschen von Zeilen

In [21]:
p = np.array([1,0,0,0,0,1,0,1,0]).reshape(3,3)
P = Matrix(p)
P

Matrix([
[1, 0, 0],
[0, 0, 1],
[0, 1, 0]])

In [22]:
a = np.array(range(9)).reshape(3,3)
A = Matrix(a)
A

Matrix([
[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])

In [23]:
P * A

Matrix([
[0, 1, 2],
[6, 7, 8],
[3, 4, 5]])

### Beispiel einer Elimination mit Vertauschung von Zeilen

In [17]:
u = np.array([1,2,3,0,-1,0,0,0,-1]).reshape(3,3)
a = permut(2,3,3) @  np.linalg.inv(ele(3,2,1)) @ np.linalg.inv(ele(2,1,1)) @ u
a, u

(array([[1., 2., 3.],
        [2., 4., 5.],
        [1., 1., 3.]]),
 array([[ 1,  2,  3],
        [ 0, -1,  0],
        [ 0,  0, -1]]))

### Die Koeffizienten von L sind die Faktoren bei der Elimination

In [8]:
l = np.array([1,0,0,2,1,0,1,3,1]).reshape(3,3)
u = np.array([1,1,2,0,3,2,0,0,-1]).reshape(3,3)

a = l@u
a, l, u

(array([[ 1,  1,  2],
        [ 2,  5,  6],
        [ 1, 10,  7]]),
 array([[1, 0, 0],
        [2, 1, 0],
        [1, 3, 1]]),
 array([[ 1,  1,  2],
        [ 0,  3,  2],
        [ 0,  0, -1]]))

In [16]:
t = ele(2,2,1) @ a
t = ele(3,1,1) @ t
t = ele(3,3,2) @ t
t

array([[ 1.,  1.,  2.],
       [ 0.,  3.,  2.],
       [ 0.,  0., -1.]])

In [17]:
Matrix(a)

Matrix([
[1,  1, 2],
[2,  5, 6],
[1, 10, 7]])

In [18]:
Matrix(l)

Matrix([
[1, 0, 0],
[2, 1, 0],
[1, 3, 1]])

In [19]:
Matrix(u)

Matrix([
[1, 1,  2],
[0, 3,  2],
[0, 0, -1]])

### Gauss Jordan

In [21]:
u = np.array([2,1,2,0,1,-1,0,0,3]).reshape(3,3)
l = np.array([1,0,0,-1,1,0,2,2,1]).reshape(3,3)
a = l @ u
l, a, u, np.linalg.inv(a)

(array([[ 1,  0,  0],
        [-1,  1,  0],
        [ 2,  2,  1]]),
 array([[ 2,  1,  2],
        [-2,  0, -3],
        [ 4,  4,  5]]),
 array([[ 2,  1,  2],
        [ 0,  1, -1],
        [ 0,  0,  3]]),
 array([[ 2.  ,  0.5 , -0.5 ],
        [-0.33,  0.33,  0.33],
        [-1.33, -0.67,  0.33]]))

In [23]:
l

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 2,  2,  1]])

In [18]:
t = ele2(2,-1,1) @ a
t = ele(3,2,1) @ t
t = ele(3,2,2) @ t
t


array([[  1.,   2.,   3.],
       [  3.,   6.,   8.],
       [ -7., -15., -19.]])

### LU Faktorisierung

In [3]:
def el(i,k,j,n=3):    # 3x3 Eliminations-Matrix 
    # von der i-ten Zeile, das k-fache der j-ten Zeile abziehen
    tmp = np.eye(n)
    tmp[i-1,j-1] = -k
    return tmp
    

In [7]:
el(2,3,1) @ A               # ruft matmul

array([[ 1.,  2.,  1.],
       [ 0.,  2., -2.],
       [ 0.,  4.,  1.]])

In [5]:
U = el(3,2,2) @ el(2,3,1) @ A     #  mat
U

array([[ 1.,  2.,  1.],
       [ 0.,  2., -2.],
       [ 0.,  0.,  5.]])

In [8]:
L = el(3,2,2) @ el(2,3,1)
L

array([[ 1.,  0.,  0.],
       [-3.,  1.,  0.],
       [ 6., -2.,  1.]])

In [12]:
Matrix(A).LUdecomposition()     # Sympy Matrix  LU-Decomposition

(Matrix([
 [1, 0, 0],
 [3, 1, 0],
 [0, 2, 1]]),
 Matrix([
 [1, 2,  1],
 [0, 2, -2],
 [0, 0,  5]]),
 [])

### Gauss-Jordan für $A^{-1}$

#### 2x2 Matrix

In [16]:
A = np.array([1,3,2,7]).reshape(2,2)
A

array([[1, 3],
       [2, 7]])

In [66]:
def augment(A):
    n = A.shape[0]
    I = np.eye(n)
    return np.append(A, I, axis=1)

 

In [22]:
t = el(2,2,1,2) @ A1
t = el(1,3,2,2) @ t
t

array([[ 1.,  0.,  7., -3.],
       [ 0.,  1., -2.,  1.]])

In [25]:
AI = t[:,2:]
AI

array([[ 7., -3.],
       [-2.,  1.]])

In [26]:
AI @ A

array([[1., 0.],
       [0., 1.]])

In [29]:
linalg.inv(A)

array([[ 7., -3.],
       [-2.,  1.]])

Weitere Aufgaben

In [58]:
def intMatrix(A):
    # true wenn alles ganzzahlig
    return np.all(A - A.astype(int) == 0)

In [46]:
def rm(r,k,n=3):
    # returns Matrix which multiplies row r of a nxn Matrix with scalar k 
    tmp = np.eye(n)
    tmp[r-1,r-1]= k
    return tmp
    

In [60]:
for i in range(1000):
    # ganzzahlige invertierbare 2x2 Matrizen
    x = np.random.randint(-7,7,4) 
    x = x.reshape(2,2)
    if abs(linalg.det(x)) > 1 and intMatrix(linalg.inv(x)):
        print(x)

[[ 4 -7]
 [ 3 -5]]
[[-2  5]
 [-1  3]]
[[-2 -7]
 [ 1  3]]


### Die Transponierte

In [6]:
a = np.array([1,3,2,3,4,1]).reshape(3,2)
Matrix(a)

Matrix([
[1, 3],
[2, 3],
[4, 1]])

In [7]:
Matrix(a.T)

Matrix([
[1, 2, 4],
[3, 3, 1]])

### Beweis Regeln für Transponierte

In [14]:
a = np.array([1,0,1,2,1,0,3,1,1]).reshape(3,3)

b = np.array([2,0,1]).reshape(3,1)

In [15]:
Matrix(a)

Matrix([
[1, 0, 1],
[2, 1, 0],
[3, 1, 1]])

In [16]:
Matrix(b)

Matrix([
[2],
[0],
[1]])

In [17]:
Matrix(a@b)

Matrix([
[3],
[4],
[7]])

In [18]:
Matrix(b.T)

Matrix([[2, 0, 1]])

In [19]:
Matrix(a.T)

Matrix([
[1, 2, 3],
[0, 1, 1],
[1, 0, 1]])

In [21]:
Matrix(b.T@a.T)

Matrix([[3, 4, 7]])

### Symmetrische Matrizen

In [25]:
a = np.array([1,3,2,3,4,1]).reshape(3,2)
Matrix(a@a.T)

Matrix([
[10, 11,  7],
[11, 13, 11],
[ 7, 11, 17]])

In [ ]:
Matrix

### Vektorräume

In [27]:
a = np.array([1,3,2,3,4,1]).reshape(3,2)
Matrix(a)

Matrix([
[1, 3],
[2, 3],
[4, 1]])

In [29]:
a = np.array([1,1,2,2,1,3,3,1,4,4,1,5]).reshape(4,3)
Matrix(a)

Matrix([
[1, 1, 2],
[2, 1, 3],
[3, 1, 4],
[4, 1, 5]])

### rref(A)

In [39]:
a = np.array([1,2,2,2,2,4,6,8,3,6,8,10]).reshape(3,4)
Matrix(a)

Matrix([
[1, 2, 2,  2],
[2, 4, 6,  8],
[3, 6, 8, 10]])

In [40]:
t = (ele(2,2,1) @ a).astype(int)
Matrix(t)

Matrix([
[1, 2, 2,  2],
[0, 0, 2,  4],
[3, 6, 8, 10]])

In [41]:
t = (ele(3,3,1)@t).astype(int)
Matrix(t)

Matrix([
[1, 2, 2, 2],
[0, 0, 2, 4],
[0, 0, 2, 4]])

In [42]:
t = (ele(3,1,2)@t).astype(int)
Matrix(t)

Matrix([
[1, 2, 2, 2],
[0, 0, 2, 4],
[0, 0, 0, 0]])

In [43]:
t = (ele(1,1,2)@t).astype(int)
Matrix(t)

Matrix([
[1, 2, 0, -2],
[0, 0, 2,  4],
[0, 0, 0,  0]])

In [47]:
t = (rm(2,0.5)@t).astype(int)
Matrix(t)

Matrix([
[1, 2, 0, -2],
[0, 0, 1,  2],
[0, 0, 0,  0]])

In [50]:
Matrix(a).rref()[0]

Matrix([
[1, 2, 0, -2],
[0, 0, 1,  2],
[0, 0, 0,  0]])

### Beispiele rref Matrix

In [52]:
a = np.array([1,2,3,2,4,6,2,6,8,2,8,10]).reshape(4,3)
Matrix(a)

Matrix([
[1, 2,  3],
[2, 4,  6],
[2, 6,  8],
[2, 8, 10]])

In [53]:
Matrix(a).rref()[0]

Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]])

In [55]:
a = np.array([1,2,3,4,2,4,8,12,3,6,7,13]).reshape(3,4)
Matrix(a)

Matrix([
[1, 2, 3,  4],
[2, 4, 8, 12],
[3, 6, 7, 13]])

In [56]:
Matrix(a).rref()[0]

Matrix([
[1, 2, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [60]:
x1 = np.array([1,2,1,3])
x2 = np.array([2,-1,0,1])
x3 = 3*x1 -2*x2
x4 = np.array([-1,1,1,2])
x5 = x1+x2-2*x4
a = np.array([x1,x2,x3,x4,x5]).T
Matrix(a)

Matrix([
[1,  2, -1, -1,  5],
[2, -1,  8,  1, -1],
[1,  0,  3,  1, -1],
[3,  1,  7,  2,  0]])

In [61]:
Matrix(a).rref()[0]

Matrix([
[1, 0,  3, 0,  1],
[0, 1, -2, 0,  1],
[0, 0,  0, 1, -2],
[0, 0,  0, 0,  0]])

### Alle Lösungen für Ax = b

In [71]:
a = np.array([1,2,2,2,2,4,6,8,3,6,8,10]).reshape(3,4)
Matrix(a)

Matrix([
[1, 2, 2,  2],
[2, 4, 6,  8],
[3, 6, 8, 10]])

In [72]:
a = np.array([1,2,2,2,1,2,4,6,8,5,3,6,8,10,7]).reshape(3,5)
Matrix(a)

Matrix([
[1, 2, 2,  2, 1],
[2, 4, 6,  8, 5],
[3, 6, 8, 10, 7]])

In [73]:
t = ele(2,2,1) @ a
Matrix(t.astype(int))

Matrix([
[1, 2, 2,  2, 1],
[0, 0, 2,  4, 3],
[3, 6, 8, 10, 7]])

In [74]:
t = ele(3,3,1) @ t
Matrix(t.astype(int))

Matrix([
[1, 2, 2, 2, 1],
[0, 0, 2, 4, 3],
[0, 0, 2, 4, 4]])

In [75]:
t = ele(3,1,2) @ t
Matrix(t.astype(int))

Matrix([
[1, 2, 2, 2, 1],
[0, 0, 2, 4, 3],
[0, 0, 0, 0, 1]])

In [76]:
a = np.array([1,2,2,2,1,2,4,6,8,5,3,6,8,10,6]).reshape(3,5)
Matrix(a)

Matrix([
[1, 2, 2,  2, 1],
[2, 4, 6,  8, 5],
[3, 6, 8, 10, 6]])

In [77]:
t = ele(2,2,1) @ a
Matrix(t.astype(int))

Matrix([
[1, 2, 2,  2, 1],
[0, 0, 2,  4, 3],
[3, 6, 8, 10, 6]])

In [78]:
t = ele(3,3,1) @ t
Matrix(t.astype(int))

Matrix([
[1, 2, 2, 2, 1],
[0, 0, 2, 4, 3],
[0, 0, 2, 4, 3]])

In [79]:
t = ele(3,1,2) @ t
Matrix(t.astype(int))

Matrix([
[1, 2, 2, 2, 1],
[0, 0, 2, 4, 3],
[0, 0, 0, 0, 0]])

### Dimension

In [6]:
a = np.array([1,2,3,1,4,1,1,2,1,3,1,2,3,1,4]).reshape(3,5)
Matrix(a)

Matrix([
[1, 2, 3, 1, 4],
[1, 1, 2, 1, 3],
[1, 2, 3, 1, 4]])

### 3x3 Matrix

In [61]:
for i in range(10000):
    # ganzzahlige invertierbare 3x3 Matrizen
    x = np.random.randint(-4,4,9) 
    x = x.reshape(3,3)
    if abs(linalg.det(x)) > 1 and intMatrix(linalg.inv(x)):
        print(list(x.flatten()))

[-3, 1, 3, -1, 1, 0, -4, 3, 1]
[1, -4, -1, 0, 2, -3, 1, -3, -2]
[-1, 0, -3, 0, -2, -3, -2, 1, -4]
[-4, -4, 1, 2, 3, -2, -3, -4, 2]
[-1, -3, -2, -2, -4, -1, -1, 0, 3]
[-1, 3, 2, 1, -3, -1, 1, -2, -3]
[1, 1, 2, 2, 0, -3, 1, 0, -2]
[2, 1, 3, 3, 2, 0, -4, -3, 2]
[1, -4, 0, 3, 3, -1, -4, 2, 1]
[3, -1, -2, -4, 3, 2, 3, -3, -1]
[2, -4, 3, 0, -3, 1, -1, -2, 0]


In [100]:
a = np.array([2, 1, 3, -1, 0, -1, 2, -3, 0]).reshape(3,3)
a, np.linalg.inv(a)

(array([[ 2,  1,  3],
        [-1,  0, -1],
        [ 2, -3,  0]]),
 array([[-3., -9., -1.],
        [-2., -6., -1.],
        [ 3.,  8.,  1.]]))

In [101]:
Matrix(a)

Matrix([
[ 2,  1,  3],
[-1,  0, -1],
[ 2, -3,  0]])

In [102]:
au = augment(a)
Matrix(au.astype(int))

Matrix([
[ 2,  1,  3, 1, 0, 0],
[-1,  0, -1, 0, 1, 0],
[ 2, -3,  0, 0, 0, 1]])

In [103]:
t = gadd(2,2,1,1) @ au
Matrix(t.astype(int))

Matrix([
[2,  1, 3, 1, 0, 0],
[0,  1, 1, 1, 2, 0],
[2, -3, 0, 0, 0, 1]])

In [104]:
t = gsub(1,3,1,1) @ t
Matrix(t.astype(int))

Matrix([
[2,  1,  3,  1, 0, 0],
[0,  1,  1,  1, 2, 0],
[0, -4, -3, -1, 0, 1]])

In [105]:
t = gadd(1,3,4,2) @ t
Matrix(t.astype(int))

Matrix([
[2, 1, 3, 1, 0, 0],
[0, 1, 1, 1, 2, 0],
[0, 0, 1, 3, 8, 1]])

In [106]:
t = gsub(1,2,1,3) @ t
Matrix(t.astype(int))

Matrix([
[2, 1, 3,  1,  0,  0],
[0, 1, 0, -2, -6, -1],
[0, 0, 1,  3,  8,  1]])

In [107]:
t = gsub(1,1,3,3) @ t
Matrix(t.astype(int))

Matrix([
[2, 1, 0, -8, -24, -3],
[0, 1, 0, -2,  -6, -1],
[0, 0, 1,  3,   8,  1]])

In [108]:
t = gsub(1,1,1,2) @ t
Matrix(t.astype(int))

Matrix([
[2, 0, 0, -6, -18, -2],
[0, 1, 0, -2,  -6, -1],
[0, 0, 1,  3,   8,  1]])

In [109]:
t = rm(1,0.5) @ t
Matrix(t.astype(int))

Matrix([
[1, 0, 0, -3, -9, -1],
[0, 1, 0, -2, -6, -1],
[0, 0, 1,  3,  8,  1]])

In [139]:
t = el(3,1,1) @ t
t = el(3,-8,2) @ t
t = el(2,0.5,3) @ t
t = el(1,3,3) @ t
t = el(1,2,2) @ t
t

array([[ -2. ,   0. ,   0. ,  -6. , -18. ,  -2. ],
       [  0. ,  -0.5,   0. ,  -1. ,  -3. ,  -0.5],
       [  0. ,   0. ,  -1. ,   3. ,   8. ,   1. ]])

In [140]:
t = rm(1,-0.5) @ t
t = rm(2,-2) @ t
t = rm(3,-1) @ t
t

array([[ 1.,  0.,  0.,  3.,  9.,  1.],
       [ 0.,  1.,  0.,  2.,  6.,  1.],
       [ 0.,  0.,  1., -3., -8., -1.]])

In [99]:
 linalg.inv(A)

array([[ 3.,  9.,  1.],
       [ 2.,  6.,  1.],
       [-3., -8., -1.]])

In [141]:
# Permutationsmatrizen

A = np.array([2, 1, 3, -1, 0, -1, 2, -3, 0]).reshape(3,3)
A = A * (-1)
A

array([[-2, -1, -3],
       [ 1,  0,  1],
       [-2,  3,  0]])

In [142]:
A1 = augment(A)
A1

array([[-2., -1., -3.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.],
       [-2.,  3.,  0.,  0.,  0.,  1.]])

In [149]:
def ele(k,i,l,j,n=3):
    # ändert nur zeile i: vom k fachen der zeile i wird das l-fache der zeile j abgezogen
    tmp = np.eye(n)
    tmp[i-1,i-1] = k
    tmp[i-1,j-1] = -l
    return tmp
    


In [151]:
t = ele(2,2,-1,1) @ A1
t = ele()

array([[-2., -1., -3.,  1.,  0.,  0.],
       [ 0., -1., -1.,  1.,  2.,  0.],
       [-2.,  3.,  0.,  0.,  0.,  1.]])

### Kern und Bild

In [ ]:
# Bestimme Rang von A und Kern von A

In [4]:
A = np.array([1,1,2,2,1,3,3,1,4,4,1,5]).reshape(4,3)
A

array([[1, 1, 2],
       [2, 1, 3],
       [3, 1, 4],
       [4, 1, 5]])

In [13]:
Matrix(A).nullspace()

[Matrix([
 [-1],
 [-1],
 [ 1]])]

In [14]:
np.linalg.matrix_rank(A)

2

In [33]:
## Gegeben die LU-Zerlegung, Bestimme eine Basis des Kerns von A

c1 = np.array([1,2,-1,4])
c2 = np.array([3,-1,1,2])
c3 = 4*c1 - 3*c2
c4 = 2*c1 - c2 - c3

In [29]:
A = np.array([c1,c2,c3,c4]).T

In [30]:
A

array([[ 1,  3, -5,  4],
       [ 2, -1, 11, -6],
       [-1,  1, -7,  4],
       [ 4,  2, 10, -4]])

In [31]:
Matrix(A).LUdecomposition()

(Matrix([
 [ 1,    0, 0, 0],
 [ 2,    1, 0, 0],
 [-1, -4/7, 1, 0],
 [ 4, 10/7, 0, 1]]),
 Matrix([
 [1,  3, -5,   4],
 [0, -7, 21, -14],
 [0,  0,  0,   0],
 [0,  0,  0,   0]]),
 [])

In [32]:
Matrix(A).nullspace()

[Matrix([
 [-4],
 [ 3],
 [ 1],
 [ 0]]),
 Matrix([
 [ 2],
 [-2],
 [ 0],
 [ 1]])]

In [34]:
Matrix(A).rowspace()

[Matrix([[1, 3, -5, 4]]), Matrix([[0, -7, 21, -14]])]

In [35]:
Matrix(A).columnspace()

[Matrix([
 [ 1],
 [ 2],
 [-1],
 [ 4]]),
 Matrix([
 [ 3],
 [-1],
 [ 1],
 [ 2]])]

### Ax = b

In [41]:
A = np.array([1,2,2,2,2,4,6,8,3,6,8,10]).reshape(3,4)
b = np.array([1,5,6]).reshape(3,1)
A, b

(array([[ 1,  2,  2,  2],
        [ 2,  4,  6,  8],
        [ 3,  6,  8, 10]]),
 array([[1],
        [5],
        [6]]))

In [42]:
C = Matrix(A).col_insert(4,Matrix(b))

In [44]:
C.rref()

(Matrix([
 [1, 2, 0, -2,  -2],
 [0, 0, 1,  2, 3/2],
 [0, 0, 0,  0,   0]]),
 (0, 2))

In [45]:
Matrix(A).nullspace()

[Matrix([
 [-2],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [ 2],
 [ 0],
 [-2],
 [ 1]])]

In [50]:
from sympy import symbols
x1, x3 = symbols('x1 x3')
X = Matrix([x1,0,x3,0])

In [55]:
# Schreibweise mit x1 .....


(Matrix(A)*X) 


Matrix([
[  x1 + 2*x3],
[2*x1 + 6*x3],
[3*x1 + 8*x3]])

In [54]:
b

array([[1],
       [5],
       [6]])

In [64]:
Ap = A[:,[0,2]]          # nur die pivot-Spalten

In [69]:
Matrix(Ap).LUsolve(Matrix(b))

Matrix([
[ -2],
[3/2]])