### MathePlus - Lineare Algebra

In [13]:
import numpy as np
import scipy
import sympy
from sympy import Matrix, symbols, solve

#### A1


In [14]:
# a
a = [1,1,-2,1,-1,2,3,1,0]
A = np.array(a).reshape((3,3))
v0, v1, v2 = A[:,0], A[:,1], A[:,2]
print(A)
print(v0-v1)

[[ 1  1 -2]
 [ 1 -1  2]
 [ 3  1  0]]
[0 2 2]


In [15]:
# b
a = [0,2,2,2,0,2,-1,1,1]
A = np.array(a).reshape((3,3))
v0, v1, v2 = A[:,0], A[:,1], A[:,2]
print(A)
print(-v0+v1+v2)

[[ 0  2  2]
 [ 2  0  2]
 [-1  1  1]]
[4 0 3]


In [16]:
# c
a = [3,1,0,1,-1,-3,-1,1,1]
A = np.array(a).reshape((3,3))
v0, v1, v2 = A[:,0], A[:,1], A[:,2]
print(A)
print(v0+v1-v2)

[[ 3  1  0]
 [ 1 -1 -3]
 [-1  1  1]]
[ 4  3 -1]


####  A2a

In [17]:
a = [2,1,-2,-1,-2,2,3,0,-1]
b = [-2,9,7]
A0 = np.array(a,dtype='float').reshape((3,3))
b = np.array(b).reshape((3,1))
print(A0)

[[ 2.  1. -2.]
 [-1. -2.  2.]
 [ 3.  0. -1.]]


In [18]:
# Augmented Matrix bilden
A = np.hstack((A0,b))
print(A)

[[ 2.  1. -2. -2.]
 [-1. -2.  2.  9.]
 [ 3.  0. -1.  7.]]


In [19]:
# Elimination
B = np.hstack((A,b))
A[1] = 2*A[1]+A[0]
A[2] = 2*A[2]-3*A[0]
print(A)

[[ 2.  1. -2. -2.]
 [ 0. -3.  2. 16.]
 [ 0. -3.  4. 20.]]


In [20]:
A[2] = A[2]-A[1]
print(A)

[[ 2.  1. -2. -2.]
 [ 0. -3.  2. 16.]
 [ 0.  0.  2.  4.]]


Die Stufenform (Echelon-Form) ist nicht eindeutig. Aber die Lösung bleibt die gleiche.

In [21]:
np.linalg.solve(A[:,:3], A[:,3:])

array([[ 3.],
       [-4.],
       [ 2.]])

In [22]:
A = np.hstack((A0,b))
A = Matrix(A).echelon_form()
A

Matrix([
[3.0,    0, -1.0,  7.0],
[  0, -6.0,  5.0, 34.0],
[  0,    0,  9.0, 18.0]])

In [23]:
sympy.linsolve([A[:,:3], A[:,3:]])

{(3.0, -4.0, 2.0)}

In [24]:
# Rücksubstitution
# x1, x2, x3 sind zunächst Symbole, nach der Lösung dann Zahlen

x1, x2, x3 = symbols("x1 x2 x3")
x3 = solve(2*x3-4, x3)[0]
x2 = solve(-3*x2 +2*x3-16,x2)[0]
x1 = solve(2*x1+x2-2*x3+2)[0]
x = np.array([x1,x2,x3]).reshape((3,1))
print(x)

[[3]
 [-4]
 [2]]


In [25]:
# Kontrolle
print(A0 @ x)

[[-2.00000000000000]
 [9.00000000000000]
 [7.00000000000000]]


In [26]:
# Alles mit einem Befehl
np.linalg.solve(A0,b)

array([[ 3.],
       [-4.],
       [ 2.]])

In [27]:
# oder mit sympy

sympy.linsolve([Matrix(A0),Matrix(b)])

{(3.0, -4.0, 2.0)}

#### A2b

In [28]:
a = [2,-4,5,3,3,7,4,-2,-3]
A0 = np.array(a,dtype='float').reshape((3,3))
b = np.array([-1,16,-3]).reshape((3,1))
A = np.hstack((A0,b))
print(A)

[[ 2. -4.  5. -1.]
 [ 3.  3.  7. 16.]
 [ 4. -2. -3. -3.]]


In [29]:
A[1] = 2*A[1]-3*A[0]
A[2] = A[2]-2*A[0]
print(A)

[[  2.  -4.   5.  -1.]
 [  0.  18.  -1.  35.]
 [  0.   6. -13.  -1.]]


In [30]:
A[2] = 3*A[2]-A[1]
print(A)

[[  2.  -4.   5.  -1.]
 [  0.  18.  -1.  35.]
 [  0.   0. -38. -38.]]


In [31]:
# Rücksubstitution
from sympy import symbols, solve
x1, x2, x3 = symbols("x1 x2 x3")
x3 = 1
x2 = solve(18*x2-x3-35,x2)[0]
x1 = solve(2*x1-4*x2+5*x3+1)[0]
x = np.array([x1,x2,x3]).reshape((3,1))
print(x)

[[1]
 [2]
 [1]]


In [32]:
# Kontrolle
print(A0 @ x == b)

[[ True]
 [ True]
 [ True]]


In [33]:
np.linalg.solve(A0,b)

array([[1.],
       [2.],
       [1.]])

In [34]:
sympy.linsolve([Matrix(A0),Matrix(b)])

{(1.0, 2.0, 1.0)}

#### A3a

In [35]:
a = [1,2,3,4,3,2,1,4,2]
b = [3,1,2,1,2,0,1,0,1,1,3,0]
A = np.array(a).reshape((3,3))
B = np.array(b).reshape((3,4))
C = A @ B
print(C)

print(f'Type: {C.shape}') 
print(f'c3,2 = {C[2,1]}')
row, col = A[2], B[:,1]
print(f'Skalarprodukt aus {row} und {col}: {np.dot(row,col)}')
print('1.Spalte:')
print(C[:,0:1])

[[10  4 13  1]
 [20  6 17  4]
 [13  3 12  1]]
Type: (3, 4)
c3,2 = 3
Skalarprodukt aus [1 4 2] und [1 0 1]: 3
1.Spalte:
[[10]
 [20]
 [13]]


In [36]:
col1 = 3*A[:,0] + 2*A[:,1] + 1*A[:,2]
print(col1)

[10 20 13]


In [37]:
row2 = 4*B[0]+3*B[1]+2*B[2]
print(row2)

[20  6 17  4]


#### A3b

In [38]:
a = [1,2,3,4,3,2,1,4]
b = [3,1,2,1,2,0]
A = np.array(a).reshape((4,2))
B = np.array(b).reshape((2,3))
C = A @ B
print(C)
print()
print(f'Type: {C.shape}') 
print(f'c3,2 = {C[2,1]}')
row, col = A[2], B[:,1]
print(f'Skalarprodukt aus {row} und {col}: {np.dot(row,col)}')
print('2.Spalte:')
print(1*A[:,0]+2*A[:,1])
print('4.Zeile:')
print(1*B[0]+4*B[1])

[[ 5  5  2]
 [13 11  6]
 [11  7  6]
 [ 7  9  2]]

Type: (4, 3)
c3,2 = 7
Skalarprodukt aus [3 2] und [1 2]: 7
2.Spalte:
[ 5 11  7  9]
4.Zeile:
[7 9 2]


In [39]:
print(1*A[:,0]+2*A[:,1])

[ 5 11  7  9]


#### A4a

In [40]:
a = [3,5,9,1,2,3,-2,-3,-7]
A = np.array(a).reshape((3,3))
print(A)

[[ 3  5  9]
 [ 1  2  3]
 [-2 -3 -7]]


In [41]:
E1 = np.eye(3)
E1[[0,1],:] = E1[[1,0],:]
print(E1)
print()
print(E1 @ A)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

[[ 1.  2.  3.]
 [ 3.  5.  9.]
 [-2. -3. -7.]]


In [42]:
E2 = np.eye(3)
E2[1] = [-3,1,0]
print(E2)
print()
print(E2 @ E1 @ A)

[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]

[[ 1.  2.  3.]
 [ 0. -1.  0.]
 [-2. -3. -7.]]


In [43]:
E3 = np.eye(3)
E3[2] = [2,0,1]
print(E3)
print()
print(E3 @ E2 @ E1 @ A)

[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]

[[ 1.  2.  3.]
 [ 0. -1.  0.]
 [ 0.  1. -1.]]


In [44]:
E4 = np.eye(3)
E4[2] = [0,1,1]
print(E4)
print()
print(E4 @ E3 @ E2 @ E1 @ A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]]

[[ 1.  2.  3.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]


#### A4b

In [45]:
a = [2,1,4,-6,-5,-8,8,3,17]
A = np.array(a).reshape((3,3))
print(A)

[[ 2  1  4]
 [-6 -5 -8]
 [ 8  3 17]]


In [46]:
E1 = np.eye(3)
E1[[1,2],:] = E1[[2,1],:]
print(E1)
print()
print(E1 @ A)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

[[ 2.  1.  4.]
 [ 8.  3. 17.]
 [-6. -5. -8.]]


In [47]:
E2 = np.eye(3)
E2[1] = [-4,1,0]
print(E2)
print()
print(E2 @ E1 @ A)

[[ 1.  0.  0.]
 [-4.  1.  0.]
 [ 0.  0.  1.]]

[[ 2.  1.  4.]
 [ 0. -1.  1.]
 [-6. -5. -8.]]


In [48]:
E3 = np.eye(3)
E3[2] = [3,0,1]
print(E3)
print()
print(E3 @ E2 @ E1 @ A)

[[1. 0. 0.]
 [0. 1. 0.]
 [3. 0. 1.]]

[[ 2.  1.  4.]
 [ 0. -1.  1.]
 [ 0. -2.  4.]]


In [49]:
E4 = np.eye(3)
E4[2] = [0,-2,1]
print(E4)
print()
print(E4 @ E3 @ E2 @ E1 @ A)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]]

[[ 2.  1.  4.]
 [ 0. -1.  1.]
 [ 0.  0.  2.]]


#### A5a

In [50]:
a = [1,3,2,-2,-3,-5,0,9,1]
A = np.array(a).reshape((3,3))
print(A)

[[ 1  3  2]
 [-2 -3 -5]
 [ 0  9  1]]


In [51]:
E1 = np.eye(3)
E1[1] = [2,1,0]
print(E1 @ A)

[[ 1.  3.  2.]
 [ 0.  3. -1.]
 [ 0.  9.  1.]]


In [52]:
E2 = np.eye(3)
E2[2] = [0,-3,1]
print(E2 @ E1 @ A)

[[ 1.  3.  2.]
 [ 0.  3. -1.]
 [ 0.  0.  4.]]


In [53]:
U = E2 @ E1 @ A
print(U)

[[ 1.  3.  2.]
 [ 0.  3. -1.]
 [ 0.  0.  4.]]


In [54]:
E1[1,0]*=-1
E1

array([[ 1.,  0.,  0.],
       [-2.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [55]:
E2[2,1]*=-1
E2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 3., 1.]])

In [56]:
L = E1 @ E2
print(L)

[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  3.  1.]]


In [57]:
print(L @ U)

[[ 1.  3.  2.]
 [-2. -3. -5.]
 [ 0.  9.  1.]]


##### LU-Zerlegung mit scipy: Hier gilt: A = P @ L @ U

In [58]:
P, L, U = scipy.linalg.lu(A)

In [59]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [60]:
print(L)

[[ 1.          0.          0.        ]
 [-0.          1.          0.        ]
 [-0.5         0.16666667  1.        ]]


In [61]:
print(U)

[[-2.         -3.         -5.        ]
 [ 0.          9.          1.        ]
 [ 0.          0.         -0.66666667]]


In [62]:
print(A)

[[ 1  3  2]
 [-2 -3 -5]
 [ 0  9  1]]


In [63]:
print(P @ L @ U)

[[ 1.  3.  2.]
 [-2. -3. -5.]
 [ 0.  9.  1.]]


##### LU-Zerlegung mit sympy

In [64]:
A1 = Matrix(A)
L, U, _ = A1.LUdecomposition()

In [65]:
L

Matrix([
[ 1, 0, 0],
[-2, 1, 0],
[ 0, 3, 1]])

In [66]:
U

Matrix([
[1, 3,  2],
[0, 3, -1],
[0, 0,  4]])

In [67]:
L @ U

Matrix([
[ 1,  3,  2],
[-2, -3, -5],
[ 0,  9,  1]])

#### A5b

In [68]:
a = [1,-1,1,-1,0,0,1,-3,5]
A = np.array(a).reshape((3,3))
print(A)

[[ 1 -1  1]
 [-1  0  0]
 [ 1 -3  5]]


In [69]:
A1 = Matrix(A)
L, U, _ = A1.LUdecomposition()
L

Matrix([
[ 1, 0, 0],
[-1, 1, 0],
[ 1, 2, 1]])

In [70]:
U

Matrix([
[1, -1, 1],
[0, -1, 1],
[0,  0, 2]])

#### A6a

In [71]:
a = [1,3,1,0,1,2,1,3,2]
A = np.array(a).reshape((3,3))
print(A)

[[1 3 1]
 [0 1 2]
 [1 3 2]]


In [72]:
E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
B = np.hstack([A,E])
print(B)

[[1. 3. 1. 1. 0. 0.]
 [0. 1. 2. 0. 1. 0.]
 [1. 3. 2. 0. 0. 1.]]


In [74]:
B[2]-=B[0]
print(B)

[[ 1.  3.  1.  1.  0.  0.]
 [ 0.  1.  2.  0.  1.  0.]
 [ 0.  0.  1. -1.  0.  1.]]


In [75]:
B[1]-=2*B[2]
print(B)

[[ 1.  3.  1.  1.  0.  0.]
 [ 0.  1.  0.  2.  1. -2.]
 [ 0.  0.  1. -1.  0.  1.]]


In [76]:
B[0]-=B[2]
print(B)

[[ 1.  3.  0.  2.  0. -1.]
 [ 0.  1.  0.  2.  1. -2.]
 [ 0.  0.  1. -1.  0.  1.]]


In [77]:
B[0]-=3*B[1]
print(B)

[[ 1.  0.  0. -4. -3.  5.]
 [ 0.  1.  0.  2.  1. -2.]
 [ 0.  0.  1. -1.  0.  1.]]


In [78]:
C = B[:,3:]
print(C)

[[-4. -3.  5.]
 [ 2.  1. -2.]
 [-1.  0.  1.]]


In [79]:
A @ C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Die inverse Matrix lässt sich auch mit numpy, scipy oder sympy bestimmen.

In [80]:
np.linalg.inv(A)

array([[-4., -3.,  5.],
       [ 2.,  1., -2.],
       [-1.,  0.,  1.]])

In [81]:
scipy.linalg.inv(A)

array([[-4., -3.,  5.],
       [ 2.,  1., -2.],
       [-1.,  0.,  1.]])

In [82]:
Matrix(A).inv()

Matrix([
[-4, -3,  5],
[ 2,  1, -2],
[-1,  0,  1]])

#### A6b


In [83]:
a = [3,2,2,-3,-4,-3,-4,-3,-3]
A = np.array(a).reshape((3,3))
print(A)

[[ 3  2  2]
 [-3 -4 -3]
 [-4 -3 -3]]


In [84]:
Matrix(A).inv()

Matrix([
[ 3,  0,  2],
[ 3, -1,  3],
[-7,  1, -6]])

#### A7a

In [85]:
A = np.arange(1,26,1).reshape((5,5))
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
P = np.eye(5)
P[[0,3],:] = P[[3,0],:]
P[[4,1],:] = P[[1,4],:]
P[[1,2],:] = P[[2,1],:]
print(P)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [87]:
B = P @ A
print(B)

[[16. 17. 18. 19. 20.]
 [11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]
 [ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


#### A7b

In [88]:
A = np.arange(1,26,1).reshape((5,5))
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [89]:
P = np.eye(5)
P[:,[0,2]] = P[:,[2,0]]
P[:,[3,4]] = P[:,[4,3]]
print(P)

[[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


In [90]:
B = A @ P
print(B)

[[ 3.  2.  1.  5.  4.]
 [ 8.  7.  6. 10.  9.]
 [13. 12. 11. 15. 14.]
 [18. 17. 16. 20. 19.]
 [23. 22. 21. 25. 24.]]


#### A8a

In [91]:
a = [1,3,0,2,0,0,1,4,1,3,1,6]
b = [1,6,7]
A = np.array(a).reshape((3,4))
print(A)

[[1 3 0 2]
 [0 0 1 4]
 [1 3 1 6]]


In [92]:
B = np.hstack((A,np.array(b).reshape((3,1))))
print(B)

[[1 3 0 2 1]
 [0 0 1 4 6]
 [1 3 1 6 7]]


In [93]:
B[2]-=B[0]
print(B)

[[1 3 0 2 1]
 [0 0 1 4 6]
 [0 0 1 4 6]]


In [94]:
B[2]-=B[1]
print(B)

[[1 3 0 2 1]
 [0 0 1 4 6]
 [0 0 0 0 0]]


Freie Variablen x2 und x4. Für die partikulare Lösung setzen wir alle freien Variablen auf 0.

In [95]:
x2 = x4 = 0
x1, x3 = symbols("x1 x3")
x3 = solve(1*x3+4*x4-6,x3)[0]
print(x3)
x1 = solve(1*x1+3*x2+0*x3+2*x4-1,x1)[0]
print(x1)

6
1


In [96]:
xp = [1,0,6,0]   # partikulare Lösung
np.dot(A,xp)

array([1, 6, 7])

Wie bestimmen nun noch den Kern. Dafür benötigen wir die letzte Spalte nicht mehr.

In [97]:
B0 = B[:,:4]
print(B0)

[[1 3 0 2]
 [0 0 1 4]
 [0 0 0 0]]


In [98]:
x2 = 1
x4 = 0
x1, x3 = symbols("x1 x3")
x3 = solve(1*x3+4*x4,x3)[0]
print(x3)
x1 = solve(1*x1+3*x2+0*x3+2*x4,x1)[0]
print(x1)

0
-3


In [99]:
v1 = [-3,1,0,0]

In [100]:
x2 = 0
x4 = 1
x1, x3 = symbols("x1 x3")
x3 = solve(1*x3+4*x4,x3)[0]
print(x3)
x1 = solve(1*x1+3*x2+0*x3+2*x4,x1)[0]
print(x1)

-4
-2


In [101]:
v2 = [-2,0,-4,1]

Kontrolle mit sympy

In [102]:
xp = np.array(xp).reshape((4,1))
v1 = np.array(v1).reshape((4,1))
v2 = np.array(v2).reshape((4,1))

In [103]:
s = 5
t = 20
x = xp + s*v1 + t*v2
A @ x

array([[1],
       [6],
       [7]])

In [104]:
a = [1,3,0,2,0,0,1,4,1,3,1,6]
b = [1,6,7]
A = np.array(a).reshape((3,4))
 

In [105]:
x1,x2,x3,x4 = symbols("x1, x2, x3, x4")
sol = sympy.linsolve((Matrix(A),Matrix(b)),(x1,x2,x3,x4))
print(sol)
#partikulare Lösung:
print(sol.args[0].subs([(x2,0),(x4,0)]))

 

{(-3*x2 - 2*x4 + 1, x2, 6 - 4*x4, x4)}
(1, 0, 6, 0)


In [106]:
x1,x2,x3,x4 = symbols("x1, x2, x3, x4")
sol = sympy.linsolve((Matrix(A),Matrix.zeros(4,1)),(x1,x2,x3,x4))
#Basisvektoren für den Kern
print(sol.args[0].subs([(x2,1),(x4,0)]))
print(sol.args[0].subs([(x2,0),(x4,1)]))

(-3, 1, 0, 0)
(-2, 0, -4, 1)


In [107]:
# weitere Kontrolle mit rref
Matrix(A).rref()[0]

Matrix([
[1, 3, 0, 2],
[0, 0, 1, 4],
[0, 0, 0, 0]])

#### A8b

In [108]:
a = [1,2,3,5,2,4,8,12,3,6,7,13]
A = np.array(a).reshape((3,4))
b = [0,6,-6]
print(A)

[[ 1  2  3  5]
 [ 2  4  8 12]
 [ 3  6  7 13]]


In [109]:
x1,x2,x3,x4 = symbols("x1, x2, x3, x4")
sol = sympy.linsolve((Matrix(A),Matrix(b)),(x1,x2,x3,x4))
sol

{(-2*x2 - 2*x4 - 9, x2, 3 - x4, x4)}

In [110]:
print(sol.args[0].subs([(x2,0),(x4,0)]))

(-9, 0, 3, 0)


In [111]:
x1,x2,x3,x4 = symbols("x1, x2, x3, x4")
sol = sympy.linsolve((Matrix(A),Matrix.zeros(4,1)),(x1,x2,x3,x4))
print(sol.args[0].subs([(x2,1),(x4,0)]))
print(sol.args[0].subs([(x2,0),(x4,1)]))

(-2, 1, 0, 0)
(-2, 0, -1, 1)


In [112]:
# weitere Kontrolle mit rref
Matrix(A).rref()[0]

Matrix([
[1, 2, 0, 2],
[0, 0, 1, 1],
[0, 0, 0, 0]])

#### A9a

In [113]:
a = [2,3,-4,2,1,0,1,1,2,-1,4,-1,-1,-2,3,2]
A = np.array(a).reshape((4,4))
print(A)

[[ 2  3 -4  2]
 [ 1  0  1  1]
 [ 2 -1  4 -1]
 [-1 -2  3  2]]


In [114]:
Matrix(A).rref()[0]

Matrix([
[1, 0,  1, 0],
[0, 1, -2, 0],
[0, 0,  0, 1],
[0, 0,  0, 0]])

In [115]:
Matrix(A).nullspace()

[Matrix([
 [-1],
 [ 2],
 [ 1],
 [ 0]])]

In [116]:
 Matrix(A).columnspace()

[Matrix([
 [ 2],
 [ 1],
 [ 2],
 [-1]]),
 Matrix([
 [ 3],
 [ 0],
 [-1],
 [-2]]),
 Matrix([
 [ 2],
 [ 1],
 [-1],
 [ 2]])]

#### A9b

In [117]:
a = [3,1,4,3,-4,1,1,0,-1,2,2,-1,6,7,-11,-1,2,-6,-8,13]
A = np.array(a).reshape((4,5))
print(A)

[[  3   1   4   3  -4]
 [  1   1   0  -1   2]
 [  2  -1   6   7 -11]
 [ -1   2  -6  -8  13]]


In [118]:
Matrix(A).rref()[0]

Matrix([
[1, 0,  2,  2, -3],
[0, 1, -2, -3,  5],
[0, 0,  0,  0,  0],
[0, 0,  0,  0,  0]])

In [119]:
Matrix(A).nullspace()

[Matrix([
 [-2],
 [ 2],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [-2],
 [ 3],
 [ 0],
 [ 1],
 [ 0]]),
 Matrix([
 [ 3],
 [-5],
 [ 0],
 [ 0],
 [ 1]])]

In [120]:
 Matrix(A).columnspace()

[Matrix([
 [ 3],
 [ 1],
 [ 2],
 [-1]]),
 Matrix([
 [ 1],
 [ 1],
 [-1],
 [ 2]])]