In [1]:
from sympy import *

In [19]:
A = Matrix([[1, -1], [3, 4], [0, 2]])
A

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [20]:
A.shape

(3, 2)

In [21]:
A.row(0)     # 1. Zeile

Matrix([[1, -1]])

In [22]:
A.col(0)     # 1. Spalte

Matrix([
[1],
[3],
[0]])

In [23]:
A.row_del(1) # 2. Zeile inplace löschen
A

Matrix([
[1, -1],
[0,  2]])

In [24]:
A.col_del(0) # 1. Spalte inplace löschen
A

Matrix([
[-1],
[ 2]])

In [32]:
A = Matrix([[1, -1], [3, 4], [0, 2]])
B = A.row_insert(0,Matrix([[1,2]]))                 # not inplace
B 

Matrix([
[1,  2],
[1, -1],
[3,  4],
[0,  2]])

In [37]:
C = B.col_insert(1,Matrix([1,2,3,4]))    
C

Matrix([
[1, 1,  2],
[1, 2, -1],
[3, 3,  4],
[0, 4,  2]])

### Gängige Matrizen erzeugen

In [4]:
eye(2)                       # Einheitsmatrix


Matrix([
[1, 0],
[0, 1]])

In [39]:
zeros(2,3)

Matrix([
[0, 0, 0],
[0, 0, 0]])

In [41]:
ones(3,2)

Matrix([
[1, 1],
[1, 1],
[1, 1]])

In [43]:
diag(1,2,3)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [44]:
diag(-1, ones(2, 2), Matrix([5, 7, 5]))

Matrix([
[-1, 0, 0, 0],
[ 0, 1, 1, 0],
[ 0, 1, 1, 0],
[ 0, 0, 0, 5],
[ 0, 0, 0, 7],
[ 0, 0, 0, 5]])

#### Determinatene, rref

In [57]:
A = Matrix([[1, 0, 1], [2, -1, 3], [4, 3, 2]])
A

Matrix([
[1,  0, 1],
[2, -1, 3],
[4,  3, 2]])

In [46]:
A.det()

-1

In [48]:
A.rref()    # das Tupel gibt die Indizes der pivot-Spalten

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [54]:
A = Matrix([[1, 2, 2, 2], [2, 4, 6, 8], [3, 6, 8, 10]])
A.rref()  

(Matrix([
 [1, 2, 0, -2],
 [0, 0, 1,  2],
 [0, 0, 0,  0]]),
 (0, 2))

In [55]:
A.nullspace()

[Matrix([
 [-2],
 [ 1],
 [ 0],
 [ 0]]),
 Matrix([
 [ 2],
 [ 0],
 [-2],
 [ 1]])]

In [56]:
A.columnspace()

[Matrix([
 [1],
 [2],
 [3]]),
 Matrix([
 [2],
 [6],
 [8]])]

In [59]:
A = Matrix([[3, -2,  4, -2], [5,  3, -3, -2], [5, -2,  2, -2], [5, -2, -3,  3]])

In [60]:
A.eigenvals()

{3: 1, -2: 1, 5: 2}

In [63]:
A.eigenvects()  # zeigt auch die Eigenwerte mit Vielfachheit

[(-2,
  1,
  [Matrix([
   [0],
   [1],
   [1],
   [1]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [1],
   [1]])]),
 (5,
  2,
  [Matrix([
   [1],
   [1],
   [1],
   [0]]),
   Matrix([
   [ 0],
   [-1],
   [ 0],
   [ 1]])])]

In [64]:
import numpy as np
from scipy import linalg

In [66]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [67]:
linalg.inv(A)                        # inverse Matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [71]:
b = np.array([5,2]).reshape(2,1)
b

array([[5],
       [2]])

In [70]:
A.dot(b)               # Matrix Multiplikation mit einer Spalte

array([[ 9],
       [23]])

In [72]:
b.T

array([[5, 2]])

### Ein Gleichungssystem lösen

In [74]:
import numpy as np
from scipy import linalg
A = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,3]).reshape(2,1)
np.linalg.solve(A, b)  # fast


array([[-7.],
       [ 6.]])

In [75]:
A.dot(np.linalg.solve(A, b)) - b  # check

array([[-8.8817842e-16],
       [ 0.0000000e+00]])

In [76]:
linalg.det(A)

-2.0

## LU

In [77]:
from scipy.linalg import lu
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
p, l, u = lu(A)
np.allclose(A - p @ l @ u, np.zeros((4, 4)))

True

In [81]:
u

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
       [ 0.        ,  0.        , -1.04      ,  3.08      ],
       [ 0.        ,  0.        ,  0.        ,  7.46153846]])

In [89]:
L = np.array([1,0,0,2,1,0,0,5,1]).reshape(3,3)
U = np.array([1,2,1,0,2,-2,0,0,5]).reshape(3,3)


In [90]:
L,  U

(array([[1, 0, 0],
        [2, 1, 0],
        [0, 5, 1]]),
 array([[ 1,  2,  1],
        [ 0,  2, -2],
        [ 0,  0,  5]]))

In [91]:
A = L.dot(U)

In [92]:
A

array([[ 1,  2,  1],
       [ 2,  6,  0],
       [ 0, 10, -5]])

In [99]:
A = np.array([1,2,3,-1,-1,0,2,1,-3]).reshape(3,3)

In [101]:
 linalg.det(A)

0.0